name: Build PDF

on:
  push:
    paths:
      - resume.md
  workflow_dispatch:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set Release Date
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}

      - name: Create output dir
        run: |
          mkdir output

      - uses: docker://pandoc/extra:3.1.1.0
        with:
          args: >-
            -H ./pandoc/header.tex
            --metadata-file="./pandoc/resume_metadata.yaml"
            --output="output/resume_${{ env.RELEASE_DATE }}.pdf"
            resume.md

      - uses: actions/upload-artifact@v3
        with:
          name: resume_${{ env.RELEASE_DATE }}_${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
          path: output
